/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto.proyecto_views;


/**
 * @author Jhon_A
 */
public class formAbastecimiento extends javax.swing.JPanel {

 

    public formAbastecimiento() {
        initComponents();

       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCocina = new javax.swing.JButton();
        btnOtros = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnInsumos = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("ABASTECIMIENTO");
        jLabel1.setIconTextGap(11);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        btnCocina.setBackground(new java.awt.Color(238, 0, 27));
        btnCocina.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCocina.setForeground(new java.awt.Color(255, 255, 255));
        btnCocina.setText("COCINA");
        btnCocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCocinaActionPerformed(evt);
            }
        });
        add(btnCocina, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 127, 39));

        btnOtros.setBackground(new java.awt.Color(238, 0, 27));
        btnOtros.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnOtros.setForeground(new java.awt.Color(255, 255, 255));
        btnOtros.setText("OTROS");
        btnOtros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtrosActionPerformed(evt);
            }
        });
        add(btnOtros, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 127, 39));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/compra_bebidas.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, 197));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/compras_cocina.jpeg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 250, 200));

        btnInsumos.setBackground(new java.awt.Color(238, 0, 27));
        btnInsumos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInsumos.setForeground(new java.awt.Color(255, 255, 255));
        btnInsumos.setText("INSUMOS");
        btnInsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsumosActionPerformed(evt);
            }
        });
        add(btnInsumos, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 127, 39));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCocinaActionPerformed
        formAbastecimientoCocina fc=new formAbastecimientoCocina();
        fc.setVisible(true);
        fc.setDefaultCloseOperation(fc.HIDE_ON_CLOSE);
    }//GEN-LAST:event_btnCocinaActionPerformed

    private void btnOtrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtrosActionPerformed
      formAbastecimientoOtros fo=new formAbastecimientoOtros();
      fo.setVisible(true);
      fo.setDefaultCloseOperation(fo.HIDE_ON_CLOSE);
    }//GEN-LAST:event_btnOtrosActionPerformed

    private void btnInsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsumosActionPerformed
        formInsumos ffc = new  formInsumos();
        ffc.setVisible(true);
        ffc.setDefaultCloseOperation(ffc.HIDE_ON_CLOSE);
    }//GEN-LAST:event_btnInsumosActionPerformed

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCocina;
    private javax.swing.JButton btnInsumos;
    private javax.swing.JButton btnOtros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
