/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto_views;

import javax.swing.table.DefaultTableModel;




public class formCaja extends javax.swing.JPanel {
    String [] encabezado1={"MESA","MOZO","CLIENTE","TOTAL","PAGO"};
    DefaultTableModel tabConsu;
    
    String [] encabezado2={"MESA","MOZO","CLIENTE","PRECIO","CANTIDAD","TOTAL","PRODUCTO","PAGO"};
    DefaultTableModel tabDet;

    public formCaja() {
        initComponents();
       tabConsu=new DefaultTableModel(null, encabezado1);
       tabConsumo.setModel(tabConsu);
       
       tabDet=new DefaultTableModel(null,encabezado2);
       tabDetalle.setModel(tabDet);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabDetalle = new javax.swing.JTable();
        btnDetalle = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabConsumo = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCobrar = new javax.swing.JButton();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();

        jCheckBox1.setText("Yape");

        jCheckBox2.setText("Efectivo");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel14.setText("Metodo de Pago:");

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("CAJA");
        jLabel1.setIconTextGap(11);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 23, -1, -1));

        tabDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabDetalle);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 349, 918, 183));

        btnDetalle.setBackground(new java.awt.Color(238, 0, 27));
        btnDetalle.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnDetalle.setForeground(new java.awt.Color(255, 255, 255));
        btnDetalle.setText("DETALLE");
        add(btnDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 104, 117, 35));

        tabConsumo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabConsumo);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 103, 625, 182));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("TOTAL A PAGAR :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 540, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Lista Detallada");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 318, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("S/.  00.00");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 540, -1, -1));

        btnCobrar.setBackground(new java.awt.Color(238, 0, 27));
        btnCobrar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnCobrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCobrar.setText("COBRAR");
        add(btnCobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(817, 615, 117, 35));

        jCheckBox3.setText("Yape");
        add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 580, -1, -1));

        jCheckBox4.setText("Efectivo");
        add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 580, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel15.setText("Metodo de Pago:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 580, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCobrar;
    private javax.swing.JButton btnDetalle;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabConsumo;
    private javax.swing.JTable tabDetalle;
    // End of variables declaration//GEN-END:variables
}
