/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto_views;

import javax.swing.table.DefaultTableModel;



/**
 * @author Jhon_A
 */
public class formReportes extends javax.swing.JPanel {
    String [] encabezado1={"CLIENTE","CATEGORIA DE ALIMENTO","MOZO","FECHA","IGV","MONTO","TOTAL"};
    DefaultTableModel tabIng;
    String [] encabezado2={"N° BOLETA","DETALLE","FECHA","MONTO"};
    DefaultTableModel tabEgre;
 

    public formReportes() {
        initComponents();
        tabIng = new DefaultTableModel(null, encabezado1);
        tabIngresos.setModel(tabIng);
        
         tabEgre = new DefaultTableModel(null, encabezado2);
        tabEgresos.setModel(tabEgre);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabIngresos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabEgresos = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("INICIO");
        jLabel1.setIconTextGap(11);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 90, -1, -1));

        tabIngresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabIngresos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 209, 874, 216));

        jButton1.setBackground(new java.awt.Color(238, 0, 27));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("FILTRAR");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 82, 127, 39));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("REPORTE");
        jLabel2.setIconTextGap(11);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 82, 155, 36));

        jButton2.setBackground(new java.awt.Color(255, 51, 102));
        jButton2.setBorderPainted(false);
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 95, 103, 9));
        add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 82, 155, 36));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("FIN");
        jLabel3.setIconTextGap(11);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 90, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("EXPORTAR INGRESOS");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 138, 156, 39));

        tabEgresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabEgresos);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 874, 216));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("EXPORTAR EGRESOS");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 138, 155, 39));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("LISTA INGRESOS");
        jLabel4.setIconTextGap(11);
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 178, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("LISTA EGRESOS");
        jLabel5.setIconTextGap(11);
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabEgresos;
    private javax.swing.JTable tabIngresos;
    // End of variables declaration//GEN-END:variables
}
